name: Deploy dev branch on dev.sugarizer.org

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update dev.sugarizer.org 
        uses: appleboy/ssh-action@v0.1.7 
        with: 
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.KEY }} 
          port: ${{ secrets.PORT }} 
          script: | 
            cd sugarizer-dev/sugarizer 
            git pull
